#!/usr/bin/env bash
# This script displays DNS information for specified domain and subdomains

get_dns_info() {
    local domain=$1
    local subdomain=$2
    local result
    
    # Use dig to get DNS information and parse with awk
    result=$(dig "$subdomain.$domain" +short | awk '{print $1}')
    
    # Determine record type (simplified to A record for this task)
    local record_type="A"
    
    echo "The subdomain $subdomain is a $record_type record and points to $result"
}

main() {
    local domain=$1
    local subdomain=$2
    
    if [ -z "$subdomain" ]; then
        # If no subdomain specified, check the default ones in order
        for sd in www lb-01 web-01 web-02; do
            get_dns_info "$domain" "$sd"
        done
    else
        # If subdomain specified, check only that one
        get_dns_info "$domain" "$subdomain"
    fi
}

# Call main function with arguments
main "$1" "$2"
